version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  frontend:
    build: ./client
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - app
    volumes:
      - ./client:/usr/src/app
